
services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-apache-container
    ports:
      - "8078:80"
    volumes:
      - .:/var/www/html

    depends_on:
      - mysql
      - redis
    networks:
      - app_network

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: training_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    container_name: phpmyadmin-container
    restart: always
    depends_on:
      - mysql
    ports:
      - "8079:80"   # phpMyAdmin => http://localhost:79
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    networks:
      - app_network

  redis:
    image: redis:7.2
    container_name: redis-container
    ports:
      - "6388:6379"   # Redis => localhost:6379
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
